# on:
#   push:
#     branches: [main]
#   workflow_dispatch:
# 
# name: build-r-package
# 
# permissions:
#   contents: write
# 
# jobs:
#   build-r-package:
#     runs-on: ubuntu-latest
#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#     steps:
# 
#     - name: Check out repository
#       uses: actions/checkout@v4

