name: YAMALE validation

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  yamale-validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Install Yamale
      run: "pip install yamale"
      
    - name: Run Yamale
      run: |
        find -iname metadata.yaml \
        -exec yamale -s schema.yaml '{}' \;